# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            lugenat.tk
tagline:          'I am studying Computer Science at Leipzig University.'
description:      ''
url:              https://lukasgehrke.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Lukas Gehrke'
  url:            lukasgehrke.de

paginate:         10
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-octicons
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

github:
  profile: 'https://github.com/lukasgehrke'

theme: jekyll-theme-cayman