# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Hydeout
tagline:          'A Jekyll theme'
description:      'The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.'
url:              https://fongandrew.github.io/hydeout
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Custom vars

github:
  repo:           https://github.com/fongandrew/hydeout

disqus:
  shortname:      hydeout

google_analytics: UA-100461102-1

version:            3.3.0
sidebar_home_link:  true
