# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Hydeout
tagline:          'A Jekyll theme'
description:      'The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.'
url:              https://fongandrew.github.io/hydeout
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5
#paginate_path:    '/page:num'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
#sidebar_blog_link:  '/'
github:
  repo:             https://github.com/fongandrew/hydeout
