# Dependencies
remote-theme:     fongandrew/hydeout
markdown:         kramdown
highlighter:      rouge

# Setup
title:            JadeTheZapper
tagline:          '재퍼의 블로그'
description:      '<a href="https://github.com/JadeTheZapper" target="_blank">You</a> must try <a href="" target="_blank">HARDER</a>'
url:              https://jadethezapper.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Zapper'
  url:            https://github.com/JadeTheZapper

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-asset-path
  - jekyll-asset-path-tag
  - asset-path-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path:       "_posts"
      type:       "posts"
    values:
      excerpt_separator:  <!--more-->
      layout:     post

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname:      https-jadethezapper-github-io

google_analytics: UA-100461102-1

# Used for Hydeout's own Github page. Feel free to remove for your
# own fork.
hydeout:
  version:        4.1.0
  repo:           https://github.com/JadeTheZapper/JadeTheZapper.github.io

img_path:         /assets/posts 